# Generated by Django 5.0.6 on 2024-06-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='categorize_word',
            field=models.ManyToManyField(related_name='words', to='word.categorizeword', verbose_name='دسته بندی کلمه'),
        ),
    ]
