# Generated by Django 5.0.6 on 2024-06-27 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesOfTheDeaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته بندی')),
                ('icon', models.FileField(upload_to='categories_deaf', verbose_name='آیکون')),
                ('url_title', models.URLField(verbose_name='عنوان در url')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_deaf', to='deaf.categoriesofthedeaf', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی ناشنوایان',
                'verbose_name_plural': 'دسته بندی های ناشنوایان',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان جمله')),
                ('video_url', models.URLField(verbose_name='url ویدیو')),
                ('category', models.ManyToManyField(related_name='sentences', to='deaf.categoriesofthedeaf', verbose_name='دسته بندی حمله')),
            ],
            options={
                'verbose_name': 'جمله',
                'verbose_name_plural': 'جمله ها',
            },
        ),
    ]
